services:
  - type: web
    name: datakinga-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main_dashboard.py --server.port 10000 --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATAKINGA_USER
        sync: false
      - key: DATAKINGA_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

  - type: cron
    name: datakinga-extractor
    runtime: docker
    dockerfilePath: ./Dockerfile
    schedule: "0 7,17,22 * * *"
    startCommand: python main_render.py
    envVars:
      - key: DATAKINGA_USER
        sync: false
      - key: DATAKINGA_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
